#!/bin/sh
### BEGIN INIT INFO
# Provides:          rtl-sdr-tcp-d0
# Description:       rtl-sdr-tcp-d0
### END INIT INFO

#====================================================================
# Set network and port.

# Set the network to bind to.
# Use 127.0.0.1 if you are using SDR software on the same host.
# Alternatively, bind to the IP address of eth0 for LAN access by
# un-commenting the following line and commenting-out NET=127.0.0.1.
#
#NET=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
NET=127.0.0.1

# Set the port to bind to.
# Default is 1234.
#
PORT=1234

# Device number
#
DEVICE=0

#====================================================================

SCRIPT="/usr/local/bin/rtl_tcp -d $DEVICE -a $NET -p $PORT"
RUNAS=root

PIDFILE=/var/run/rtl-sdr-tcp-d0.pid
LOGFILE=/var/log/rtl-sdr-tcp-d0.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f rtl-sdr-tcp-d0 remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac